name: Build and Deploy Hugo Site (with rsync)

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.1'

      - name: Build Hugo Site
        run: hugo --minify

      - name: Setup SSH Agent and Deploy with rsync
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via rsync over SSH
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            public/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_TARGET_DIR }}
